#
# Automatically generated by 'fd2python --callback'
#
from ajax_uiwrap import *
import __main__
import sys

# Note: For some reason, the sys.exit(0) call doesn't work.  It returns back
# to the C routine that called the python routine.
def do_main_configure_pulldown(obj, arg):
  pass

def do_main_file_pulldown(obj, arg):
  n = fl_get_menu(obj);
  if n == 4:
    C_EXIT(n);
  else:
    fl_show_messages("This really should execute a FILE pulldown");
  pass

def do_main_help_pulldown(obj, arg):
  n = fl_get_menu(obj);
  if n == 1:
    fl_show_messages("Sorry there is no CONTENT help.");
  elif n == 2:
    fl_show_messages("Created by John H. Merritt.");
  pass

